### ISSUE TITLE
Using fmadd or fmsub in cmul

### ISSUE THREAD

**Issue by flori-uni** [aff3ct/MIPP#16]
Hi,

have you thought about using fmadd or fmsub inside the cmul?
https://github.com/aff3ct/MIPP/blob/397ff5bd40cf6f6a0b8b92e2eefb6668deba63a4/src/mipp.h#L882-L883

```cpp
auto v3_re = mipp::fmsub<T>(v1.val[0], v2.val[0], mipp::mul<T>(v1.val[1], v2.val[1]));
auto v3_im = mipp::fmadd<T>(v1.val[0], v2.val[1], mipp::mul<T>(v1.val[1], v2.val[0]));
```

**Comment by kouchy** [comment]
Hi, no I missed that, you can add it in a PR if you want :-)!

**Comment by flori-uni** [comment]
Mhm okay... integer types cause some issues ...

**Comment by kouchy** [comment]
Ah yes I see, I will do a specialization only for float and double types.
