### ISSUE TITLE
Clearify using deinterleave 

### ISSUE THREAD

**Issue by flori-uni** [aff3ct/MIPP#17]
I tried to use the new Regx2 functionality in combination with complex numbers. 
```cpp
#include "../src/mipp.h"
#include <complex>
int main(){

    std::complex<float> data[16];
    data[0].real(0);
    data[0].imag(1);
    data[1].real(2);
    data[1].imag(3);
    data[2].real(4);
    data[2].imag(5);
    data[3].real(6);
    data[3].imag(7);
    data[4].real(8);
    data[4].imag(9);
    data[5].real(10);
    data[5].imag(11);
    data[6].real(12);
    data[6].imag(13);
    data[7].real(14);
    data[7].imag(15);
    data[8].real(16);
    data[8].imag(17);
    data[9].real(18);
    data[9].imag(19);
    mipp::Regx2<float> a;
    a.load((float*)data);
    a = a.deinterleave();
    std::cout<< a[0] << std::endl;
}
```
This produces
```
[     0,     16,      1,     17 |      2,     18,      3,     19 |      4,      0,      5,      0 |      6,      0,      7,      0]
```

So from my point of view they are still interleaved? I would have expected that a[0] contains all real parts?

**Comment by kouchy** [comment]
Yes I will have expected the same... What are your compiler and ISA ?

**Comment by kouchy** [comment]
I tried your code on a AVX-512F machine with GCC 9.2 and I've got:
`[     0,      2,      4,      6 |      8,     10,     12,     14 |     16,     18,      0,      0 |      0,      0,      0,      0]`

Here is my command line to compile: 
`g++ --std=c++11 complex.cpp -mavx512f`

I really don't understand your result.

**Comment by flori-uni** [comment]
Mhm okay. That seems to a bug by the SDE ... Using a native machine works fine. Sry

**Comment by flori-uni** [comment]
The reason why i started trying this: I'm using the (new) permute methods. So interleaving is done by:
```cpp
__m512i idx = _mm512_setr_epi32(0, 16, 1, 17, 2, 18, 3, 19, 4, 20, 5, 21, 6, 22, 7, 23);
auto hi = _mm512_permutex2var_ps(m_re, idx, m_im);

auto idx = _mm512_setr_epi32(8, 24, 9, 25, 10, 26, 11, 27, 12, 28, 13, 29, 14, 30, 15, 31);
auto lo = _mm512_permutex2var_ps(m_re.r, idx, m_im.r);
```
and deinterleaving
```cpp
__m512i realIndicies = _mm512_setr_epi32(0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30);
__m512i imagIndicies = _mm512_setr_epi32(1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31);
auto  m_re = _mm512_permutex2var_ps(hi, realIndicies, lo);
auto m_im = _mm512_permutex2var_ps(hi, imagIndicies, lo);
``` 

Maybe that provides a bit more performance? :wink:

**Comment by kouchy** [comment]
Yes I agree this is better than the actual implem, especially for the `mipp::interleave` operation in AVX-512 :-)

**Comment by flori-uni** [comment]
I could provide a PR for this part?

**Comment by kouchy** [comment]
Yes if you are motivated, I think it is nice to have faster `mipp::interleave` \ `mipp::deinterleave` operations. And even more as they are now a key to perform complex operations after.

**Comment by flori-uni** [comment]
Okay. I will focus on the AVX512 implementations.
