### ISSUE TITLE
More simple comparison

### ISSUE THREAD

**Issue by flori-uni** [aff3ct/MIPP#2]
I'm currently evaluating multiple SIMD libs. 
While looking in the code I recognized, that the less-than comparisons are realized a bit complicated for my opinion.
https://github.com/aff3ct/MIPP/blob/2a262917c52c338394c17240a2626f0f333638d4/src/mipp_impl_AVX.hxx#L1993

Wouldn't it be enough to check for a simple greater with 2 flipped arguments, instead of calculating not greater-equal?

**Comment by kouchy** [comment]
Hi @flori-uni,

I think your are right, thx! I missed that...
Do you want to propose a pull request? If not I will change that myself when I will have some time.
