### ISSUE TITLE
performance in debug mode with Visual Studio x64 avx2

### ISSUE THREAD

**Issue by zchrissirhcz** [aff3ct/MIPP#25]
Hi, MIPP Team

Thansk for providing this very-very-easy-to-get-started-to-use SIMD library.

I would like to calculate the dot-product result of two float32 array:
```c++
float dotproduct(size_t len, float* va, float* vb)
```

I implement this function by calling SIMD wrapper functions, from 3 libraries:
- [OpenCV universal intrinsics](https://docs.opencv.org/master/df/d91/group__core__hal__intrin.html)
- [MIPP](https://github.com/aff3ct/MIPP)
- [Eigen](http://gitlab.com/libeigen/eigen)

With `/AVX2` enabled, I test the performance of these implementations in both Release and Debug mode. Specifically, I use `len=200000000`, and got:

Release Mode:
>impl1(Naive),   result is -5290.376953, time cost is 221.296500 ms
impl2(OpenCV),  result is -5290.970215, time cost is 66.737100 ms
impl4(MIPP),    result is -5290.970703, time cost is 65.687000 ms
impl5(Eigen),   result is -5290.747070, time cost is 74.621900 ms

Debug Mode:
>impl1(Naive),   result is -5290.376953, time cost is 498.087700 ms
impl2(OpenCV),  result is -5290.986328, time cost is 1607.252700 ms
impl4(MIPP),    result is -5290.986816, time cost is **3864.709700 ms**
impl5(Eigen),   result is -5290.748047, time cost is 2963.119900 ms

i.e. **In debug mode, MIPP cost 3864 ms where OpenCV/Eigen cost less time** (still with `/AVX2` enabled)

I'm not familiar with the implementation of these SIMD wrappers, nor do I have much experience with SIMD programming. Just wondering if there is some config I missing, to speed up MIPP's performance in Debug mode? Or, is this is a known issue and would be resolved in the future?

The whole implementation and comparison can be found [here](https://github.com/zchrissirhcz/pixel/blob/8550af2090bca836d0a75873387361fa99fee113/dotproduct/main.cpp).

**Comment by zchrissirhcz** [comment]
![image](https://user-images.githubusercontent.com/3831847/107879682-4ce4ee00-6f15-11eb-8dc3-2104859af887.png)

![image](https://user-images.githubusercontent.com/3831847/107879709-684ff900-6f15-11eb-82df-66a2ac81ee77.png)



```c++

// OpenCV universal intrinsics based implementation
float dotproduct2(size_t len, float* va, float* vb)
{
    size_t step = sizeof(cv::v_float32)/sizeof(float);
    cv::v_float32 v_sum = cv::vx_setzero_f32();
    for (size_t i=0; i<len; i+=step)
    {
        cv::v_float32 v1 = cv::vx_load(va+i);
        cv::v_float32 v2 = cv::vx_load(vb+i);
        v_sum += v1 * v2;
    }

    float sum = cv::v_reduce_sum(v_sum);

    size_t remain_begin = len -1 - (len % step);
    for (size_t i=remain_begin; i<len; i++) {
        sum += va[i] * vb[i];
    }

    return sum;
}

// MIPP based implementation
float dotproduct4(size_t len, float* va, float* vb)
{
    constexpr int step = mipp::N<float>();
    //printf("--- mipp::N<float>() is %d\n", mipp::N<float>());
    mipp::Reg<float> ra, rb, rc;
    rc.set0();
    for (size_t i=0; i<len; i+=step) {
        ra.load(va + i);
        rb.load(vb + i);
        rc += ra * rb;
    }

    float sum = rc.sum();

    size_t remain_begin = len -1 - (len % step);
    for (size_t i=remain_begin; i<len; i++) {
        sum += va[i] * vb[i];
    }

    return sum;
}

// Eigen based implementation
float dotproduct5(size_t len, float* va, float* vb)
{
    Eigen::Map<Eigen::Matrix<float, 1, Eigen::Dynamic, Eigen::RowMajor>> vva(va, len);
    Eigen::Map<Eigen::Matrix<float, 1, Eigen::Dynamic, Eigen::RowMajor>> vvb(vb, len);
    float res = vva.dot(vvb);
    return res;
}
```

**Comment by kouchy** [comment]
Hi @zchrissirhcz,

First, thx for your interest in MIPP.

It does not surprise me that you have bad performance in debug mode, MIPP relies a lot in the "function inlining" capacity of your compiler. Which compiler are you using ? MSVC I supposed ?

In debug mode the compiler is not very aggressive to inline the functions so you can try to use the `/Ob3` compiler option to set more aggressive inlining (see https://docs.microsoft.com/fr-fr/cpp/build/reference/ob-inline-function-expansion?view=msvc-160).

I hope it helps.

**Comment by zchrissirhcz** [comment]
Thanks for your explanation, @kouchy .

Yes, the compiler I am using is MSVC. 

In debug mode, by specifing `/Ob3` to compile option, it really speed up, MIPP time cost from ~3800ms to ~1000ms, and whole result is:

>time cost for random assign is 11280.405600 ms
impl1(Naive),   result is -5290.376953, time cost is 503.579000 ms
impl2(OpenCV),  result is -5291.520020, time cost is 172.810900 ms
impl4(MIPP),    result is -5291.520508, time cost is **1005.270700 ms**
impl5(Eigen),   result is -5290.748047, time cost is 260.357800 ms
impl6(xsimd),   result is -5291.520508, time cost is 1266.117400 ms
