### ISSUE TITLE
overflow warnings with GCC

### ISSUE THREAD

**Issue by ilmai** [aff3ct/MIPP#28]
I'm getting the following warning (or in this case errors as I have warnings as errors enabled) when trying to compile MIPP on an ARM64 platform:

`[build] /home/pi/convolution-thing/source/../externals/MIPP/src/mipp_impl_NEON.hxx:2181:38: error: overflow in conversion from ‘int’ to ‘int16_t’ {aka ‘short int’} changes value from ‘32768’ to ‘-32768’ [-Werror=overflow]`

Looks like the AVX version adds this, so it knows it's going to overflow, but only hides this in this instance in Visual Studio:

```
#ifdef _MSC_VER
#pragma warning( disable : 4309 )
#endif
```

What is the code actually trying to do? If it knows it's going to overflow, why not just use -0x8000 directly, instead of 0x8000 which overflows to -0x8000 (and ditto for other integer types).

**Comment by kouchy** [comment]
Hi @ilmai,

It was a mistake, I accepted your pull request https://github.com/aff3ct/MIPP/pull/29.

Thx again.
