### ISSUE TITLE
Plan for ARM SVE support

### ISSUE THREAD

**Issue by qiangmgit** [aff3ct/MIPP#31]
Hi, does MIPP plan to support ARM SVE? Thanks

**Comment by kouchy** [comment]
Hi @qiangmgit,

Yes we plan to support ARM SVE, we are currently working on it. However, at this time, it is a little bit challenging due to some compiler limitations (no support for sizeless structures).

**Comment by qiangmgit** [comment]
Thanks, looking forward to it!
