### ISSUE TITLE
Doubt regarding horizontal sum in MIPP

### ISSUE THREAD

**Issue by Darshcg** [aff3ct/MIPP#42]
Hi MIPP team,

Thank you for your great work and contribution. 

I basically had a doubt about the availability of vectorized horizontal sum in MIPP. I want to perform the sum of all the elements in a Registers using vector instructions. Is it possible to assist me in finding the same implementation in MIPP?

Basically, I have 32 elements(each element of 8 bits) in a 256-bit register; I want to add all the 32 elements using the vector instructions. 

Look forward to hearing from you.

Thanks,
Darshan

**Comment by kouchy** [comment]
Hi @Darshcg,

Thx and glad if you like MIPP.

Yes you can do this with MIPP, you have the `mipp::sum` function that do exactly what you want.
You can see the prototype in the documentation here: https://github.com/aff3ct/MIPP#reductions-horizontal-functions.

I hope it helps.
