### ISSUE TITLE
Can you add an example about image processing?

### ISSUE THREAD

**Issue by libaineu2004** [aff3ct/MIPP#49]
The examples here are not rich enough
https://github.com/aff3ct/MIPP/tree/master/examples

Can you add an example of digital image processing algorithms such as threshold/canny/sobel?

**Comment by kouchy** [comment]
Hi @libaineu2004,

Very glad if you are using this library.

However, maybe I need to remind you that this is a open source code and when you want to ask something you should show a little courtesy ;-).

Best regards.
