### ISSUE TITLE
sizeof(reg_2<xxx>) return 64 instead of 32 with AVX512

### ISSUE THREAD

**Issue by guignont** [aff3ct/MIPP#51]
Hello the following code with AVX512:
```
  std::cout << sizeof(mipp::Reg<int32_t>) << std::endl;
  std::cout << sizeof(mipp::Reg_2<int32_t>) <<  std::endl;

  std::cout << sizeof(mipp::reg) << std::endl;
  std::cout << sizeof(mipp::reg_2) << std::endl;

```
Gives the following result
64
64
64
32

while the expected result is:
64
32
64
32

When  I look at Reg_2 I see:

`virtual ~Reg_2() = default;
`

There is no reason to have a virtual destructor here (Reg do not have one).
Removing "virtual" solves the problem.

A+
Thomas

**Comment by kouchy** [comment]
Oh! You are right :-). Thank you, I merged your fix!
