### ISSUE TITLE
Include dirs not set correctly for BUILD_INTERFACE, and alias target for MIPP::mipp not set

### ISSUE THREAD

**Issue by MeijisIrlnd** [aff3ct/MIPP#55]
Heya - when consuming via FetchContent as opposed to a system-wide install, the `target_include_directories` are set to `${CMAKE_CURRENT_SOURCE_DIR}/src`, which doesn't exist or have any of the headers in it. Additionally, the install target specifies `NAMESPACE MIPP::`, but an alias isn't set up for this - meaning when consumed via FetchContent, the correct way to link to the target is with `target_link_libraries(<YourTarget> PRIVATE mipp)` as opposed to `target_link_libraries(<YourTarget> PRIVATE MIPP::mipp)`. 
I'll link to this issue in a PR with fixes to these issues, hope it helps!

**Comment by kouchy** [comment]
Thx @MeijisIrlnd! I merged your PR.
