### ISSUE TITLE
`toReg` is inconsistent and under-documented

### ISSUE THREAD

**Issue by Swire42** [aff3ct/MIPP#57]
It seems that toReg maps `0` to `0` and `1` to `~0` when using intrinsics, but that it maps `0` to `0` and `1` to `1` when intrinsics are disabled.

The documentation only states "Converts the mask m into a register of type T, the number of elements N has to be the same for the mask and the register.", so it is not possible to tell which behavior is correct.

---

SIMD (tested on AVX and NEON):
```cpp
#include <iostream>

#include "mipp.h"

using namespace std;
using namespace mipp;

int main() {
    cout << toReg<uint32_t>(Reg<uint32_t>(42) > Reg<uint32_t>(24)) << endl;
}
```
Output:
```
[4294967295, 4294967295, 4294967295, 4294967295]
```

no SIMD:
```cpp
#include <iostream>

#define MIPP_NO_INTRINSICS
#include "mipp.h"

using namespace std;
using namespace mipp;

int main() {
    cout << toReg<uint32_t>(Reg<uint32_t>(42) > Reg<uint32_t>(24)) << endl;
}
```
Output:
```
1
```

**Comment by kouchy** [comment]
Done here: https://github.com/aff3ct/MIPP/commit/f727ba9997c68ea796e181d1e6f77bc7409e80cb
